---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    uses: lpenz/omnilint/.github/workflows/omnilint.yml@v0.5.2
  rust:
    uses: lpenz/ghworkflow-rust/.github/workflows/rust.yml@v0.23.4
    with:
      coveralls: true
      deb: true
      publish_cratesio: true
      publish_github_release: true
      publish_github_release_files: |
        target/release/wonok
      publish_packagecloud: true
      publish_packagecloud_repository: |
        ["debian/debian/bookworm",
         "ubuntu/ubuntu/noble"]
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
